import { type TSESLint } from '@typescript-eslint/utils';

export type NodecfdiSettings = {
  /**
   * Vitest support.
   */
  vitest?: boolean;
  /**
   * AdonisJS support.
   */
  adonisjs?: boolean;
  /**
   * Vue3 Support.
   */
  vue?: boolean;
  /**
   * SonarJS support
   */
  sonarjs?: boolean;
  /**
   * Node using n support
   */
  n?: boolean;
  /**
   * Typescript eslint project service option
   */
  projectService?: TSESLint.FlatConfig.ParserOptions['projectService'];
  /**
   * This setting apply some ignore patterns to the whole config.
   */
  ignores?: {
    /**
     * Some commonly ignored folders.
     */
    recommended?: boolean;
    /**
     * With this setting, Nodecfdi will ignore all the files that are currently ignored by git. Chances are that if you are ignoring a file in git, you don't want to lint it, which usually is the case with temporary and autogenerated files.
     */
    inheritedFromGitignore?: boolean;
    /**
     * Include additional ignore files paths or regex paths to ignore on current eslint config
     */
    additional?: string[];
  };
};
